# Test config file
fail_on: high

ignore:
  - ".venv/**"
  - "tests/**"

output:
  format: summary

ai:
  provider: openai
  timeout: 30

scanners:
  sca:
    enabled: true
    ignore_unfixed: true
    severity:
      - CRITICAL
      - HIGH
  sast:
    enabled: false
  iac:
    enabled: false
  container:
    enabled: false
