version: 1

project:
  name: lucidshark
  languages: [python]

pipeline:
  linting:
    enabled: true
    tools: [ruff]

  type_checking:
    enabled: true
    tools: [mypy]

  security:
    enabled: true
    tools:
      - name: trivy
        domains: [sca]
      - name: opengrep
        domains: [sast]

  testing:
    enabled: true
    tools: [pytest]

  coverage:
    enabled: true
    tools: [coverage_py]
    threshold: 80

  duplication:
    enabled: true
    threshold: 5.0
    min_lines: 7
    tools: [duplo]
    exclude:
      - "htmlcov/**"
      - "docs/**"
      - "tests/**"

fail_on:
  linting: error
  type_checking: error
  security: high
  testing: any
  coverage: below_threshold
  duplication: above_threshold

exclude:
  - "**/.venv/**"
  - "**/__pycache__/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.git/**"
  - "**/.github/**"
  - "**/.lucidshark/**"
  - "**/lucidshark.egg-info/**"
  - "tests/integration/projects/**"
