version: 1

project:
  name: lucidshark
  languages: [python]

pipeline:
  linting:
    enabled: true
    tools:
      - name: ruff

  type_checking:
    enabled: true
    tools:
      - name: mypy

  security:
    enabled: true
    tools:
      - name: trivy
        domains: [sca]
      - name: opengrep
        domains: [sast]

  testing:
    enabled: true
    tools:
      - name: pytest

  coverage:
    enabled: true
    tools:
      - name: coverage_py
    threshold: 80

  duplication:
    enabled: true
    threshold: 5.0
    min_lines: 7
    tools:
      - name: duplo
    exclude:
      - "docs/**"
      - "tests/**"

fail_on:
  linting: error
  type_checking: error
  security: high
  testing: any
  coverage: below_threshold
  duplication: above_threshold

# Global excludes - comprehensive list for Python projects
exclude:
  # Git and IDE
  - "**/.git/**"
  - "**/.github/**"
  - "**/.lucidshark/**"
  # Python virtual environments
  - "**/.venv/**"
  - "**/venv/**"
  # Python caches
  - "**/__pycache__/**"
  - "**/.mypy_cache/**"
  - "**/.pytest_cache/**"
  - "**/.ruff_cache/**"
  # Build artifacts
  - "**/dist/**"
  - "**/build/**"
  - "**/*.egg-info/**"
  - "**/.eggs/**"
  # Coverage reports
  - "**/htmlcov/**"
  # Test automation
  - "**/.tox/**"
  - "**/.nox/**"
  # Project-specific
  - "tests/integration/projects/**"
  - ".tasks/**"
