# LucidScan GitLab CI Template
# Copy this to your .gitlab-ci.yml or include it as a template
#
# Usage:
#   include:
#     - remote: 'https://raw.githubusercontent.com/voldeq/lucidscan/main/ci-templates/gitlab-ci.yml'
#
# Or copy the jobs below into your existing .gitlab-ci.yml

variables:
  LUCIDSCAN_VERSION: "latest"
  LUCIDSCAN_FAIL_ON: ""  # Set to critical, high, medium, or low

# Reusable hidden job template
.lucidscan-base:
  image: ghcr.io/voldeq/lucidscan:latest
  script:
    - |
      ARGS=""
      if [ -n "$LUCIDSCAN_FAIL_ON" ]; then
        ARGS="$ARGS --fail-on $LUCIDSCAN_FAIL_ON"
      fi
      lucidscan $SCAN_ARGS $ARGS

# Full security scan (SCA + SAST + IaC)
lucidscan:
  extends: .lucidscan-base
  stage: test
  variables:
    SCAN_ARGS: "--all"
  allow_failure: false
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - gl-sast-report.json
    when: always
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Alternative: Individual scan jobs for parallel execution
lucidscan-sca:
  extends: .lucidscan-base
  stage: test
  variables:
    SCAN_ARGS: "--sca"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lucidscan-sast:
  extends: .lucidscan-base
  stage: test
  variables:
    SCAN_ARGS: "--sast"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

lucidscan-iac:
  extends: .lucidscan-base
  stage: test
  variables:
    SCAN_ARGS: "--iac"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Container image scanning (for projects that build Docker images)
lucidscan-container:
  extends: .lucidscan-base
  stage: test
  variables:
    SCAN_ARGS: "--container --image $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - job: build-image  # Assumes you have a job that builds the image

# Blocking scan for production branches
lucidscan-blocking:
  extends: .lucidscan-base
  stage: test
  variables:
    SCAN_ARGS: "--all --fail-on high"
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
